export const ROVER_FETCH = 'ROVER_FETCH'
export const SET_ROVER = 'SET_ROVER'
export const MANIFEST_FETCH = 'MANIFEST_FETCH'
export const SET_MANIFEST = 'SET_MANIFEST'
export const PHOTO_FETCH = 'PHOTO_FETCH'
